In [256]:
import numpy as np
from sklearn.decomposition import PCA
from numpy import linalg as LA

stocks = np.loadtxt( 'T8-4.DAT' )
stocks = stocks
stocks.shape

(103, 5)

In [321]:
# A
S = np.cov(stocks.transpose())

pca = PCA()
pc_stocks = pca.fit_transform(stocks)
pc_stocks = [pc/LA.norm(pc) for pc in pc_stocks]
for i in range(10): 
    print("The " + str(i+1) +"th principal component is")
    print(pc_stocks[i])
 


The 1th principal component is
[ 0.60753709  0.24803731  0.74839753 -0.02902622 -0.09184111]
The 2th principal component is
[-0.72295646  0.26546277 -0.0114496   0.11225131 -0.62779935]
The 3th principal component is
[ 0.59405813 -0.39567605 -0.32321977 -0.47361773  0.40218234]
The 4th principal component is
[ 0.51450498  0.63604439  0.4850611  -0.00606369  0.30888692]
The 5th principal component is
[-0.87489342 -0.30271729  0.22324466  0.22863646 -0.20201717]
The 6th principal component is
[-0.09603161 -0.33936507 -0.0156215   0.92883658  0.11237377]
The 7th principal component is
[-0.70261312  0.44604602 -0.53438076  0.012544   -0.14716521]
The 8th principal component is
[-0.29910307  0.59740582  0.33816682  0.50205704  0.43269569]
The 9th principal component is
[ 0.83402468 -0.38011139  0.08482968 -0.36967597 -0.12673503]
The 10th principal component is
[ 0.61093689  0.4519145  -0.04669779 -0.33124033 -0.55734061]


In [324]:
# B
eigenValues, eigenVectors = LA.eig(S)

idx = eigenValues.argsort()[::-1]   
eigenValues = eigenValues[idx]
eigenVectors = eigenVectors[:,idx]

expl_var_pca = sum(pca.explained_variance_ratio_[0:3])
expl_var_cov = sum(eigenValues[0:3])/np.matrix.trace(S)

print("The variance explained by the first 3 pc is " + str(expl_var_cov*100)+"%.")
print(expl_var_pca)

The variance explained by the first 3 pc is 89.88094845492047%.
0.898809484549204


In [323]:
# B 
for i in range(3): 
    print(pc_stocks[i])

[ 0.60753709  0.24803731  0.74839753 -0.02902622 -0.09184111]
[-0.72295646  0.26546277 -0.0114496   0.11225131 -0.62779935]
[ 0.59405813 -0.39567605 -0.32321977 -0.47361773  0.40218234]
