In [7]:
import numpy as np
from sklearn.decomposition import PCA
from numpy import linalg as LA

stocks = np.loadtxt( 'T8-4.DAT' )
stocks = stocks.transpose()
stocks.shape

(5, 103)

In [64]:
# A
S = np.cov(stocks)

pca = PCA()
pc_stocks = pca.fit_transform(stocks)
pc_stocks = pc_stocks.transpose()
pc_stocks = [pc/LA.norm(pc) for pc in pc_stocks]
for i in range(5): 
    print("The " + str(i+1) +"th principal component is")
    print(pc_stocks[i])
 


The 1th principal component is
[-0.44685894 -0.34408014 -0.29708507  0.51427881  0.57374534]
The 2th principal component is
[-0.30354746  0.27626382  0.0203242   0.64811138 -0.64115194]
The 3th principal component is
[-0.51503917 -0.19636436  0.82058017 -0.14641455  0.03723791]
The 4th principal component is
[-0.4928597   0.75281352 -0.19487324 -0.30664593  0.24156535]
The 5th principal component is
[0.4472136 0.4472136 0.4472136 0.4472136 0.4472136]


In [71]:
# B
S = np.corrcoef(stocks)

eigenValues, eigenVectors = LA.eigh(S)


idx = eigenValues.argsort()[::-1]   
eigenValues = eigenValues[idx]
eigenVectors = eigenVectors[:,idx]
##eigenValues = eigenValues.reverse()


expl_var_pca = sum(pca.explained_variance_ratio_[2:4])
expl_var_cov = sum(eigenValues[0:3])/np.matrix.trace(S)

print(eigenVectors)
print(expl_var_cov)

[[-0.46908321  0.36800696  0.60431522  0.36302278 -0.3841216 ]
 [-0.53240549  0.23646236  0.13610618 -0.6292079   0.49618794]
 [-0.46516333  0.3151795  -0.7718281   0.28896583 -0.07116948]
 [-0.38734594 -0.58503725 -0.09336192 -0.38125151 -0.59466408]
 [-0.36068206 -0.60584628  0.10882629  0.49341454  0.49755167]]
0.8689597060661909


In [62]:
# B 
for i in range(3): 
    print(pc_stocks[i])

[-0.44685894 -0.34408014 -0.29708507  0.51427881  0.57374534]
[-0.30354746  0.27626382  0.0203242   0.64811138 -0.64115194]
[-0.51503917 -0.19636436  0.82058017 -0.14641455  0.03723791]
